{
  "additionalMetadata": {
    "cna": "mitre",
    "cveId": "CVE-2023-33595",
    "description": "CPython v3.12.0 alpha 7 was discovered to contain a heap use-after-free via the function ascii_decode at /Objects/unicodeobject.c.",
    "reason": "Improve version ranges to indicate fix",
    "references": [
      "https://github.com/python/cpython/issues/103824",
      "https://github.com/python/cpython/pull/103993/commits/c120bc2d354ca3d27d0c7a53bf65574ddaabaf3a"
    ]
  },
  "adp": {
    "affected": [
      {
        "collectionURL": "https://github.com",
        "cpes": [
          "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
        ],
        "packageName": "python/cpython",
        "product": "CPython",
        "repo": "https://github.com/python/cpython",
        "vendor": "Python Software Foundation",
        "versions": [
          {
            "lessThan": "3.12.0-alpha8",
            "status": "affected",
            "version": "3.12.0-alpha0",
            "versionType": "python"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}