{
  "additionalMetadata": {
    "cna": "psf",
    "cveId": "CVE-2024-8088",
    "description": "There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.ZipFile\" like \"namelist()\", \"iterdir()\", \"extractall()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected.",
    "needsReview": true,
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/python/cpython/commit/795f2597a4be988e2bb19b69ff9958e981cb894e",
      "https://github.com/python/cpython/commit/8c7348939d8a3ecd79d630075f6be1b0c5b41f64",
      "https://github.com/python/cpython/commit/dcc5182f27c1500006a1ef78e10613bb45788dea",
      "https://github.com/python/cpython/issues/122905",
      "https://github.com/python/cpython/pull/122906",
      "https://mail.python.org/archives/list/security-announce@python.org/thread/GNFCKVI4TCATKQLALJ5SN4L4CSPSMILU/"
    ]
  },
  "adp": {
    "affected": [
      {
        "collectionURL": "https://github.com",
        "cpes": [
          "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
        ],
        "packageName": "python/cpython",
        "product": "CPython",
        "repo": "https://github.com/python/cpython",
        "vendor": "Python Software Foundation",
        "versions": [
          {
            "lessThanOrEqual": "3.13.0",
            "status": "affected",
            "version": "0",
            "versionType": "python"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}