{
  "additionalMetadata": {
    "cna": "github_m",
    "cveId": "CVE-2024-26130",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55",
      "https://github.com/pyca/cryptography/pull/10423",
      "https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4"
    ]
  },
  "adp": {
    "affected": [
      {
        "collectionURL": "https://pypi.org",
        "cpes": [
          "cpe:2.3:a:cryptography_project:cryptography:*:*:*:*:*:python:*:*"
        ],
        "packageName": "cryptography",
        "packageType": "python",
        "product": "cryptography",
        "vendor": "pyca",
        "versions": [
          {
            "lessThan": "42.0.4",
            "status": "affected",
            "version": "38.0.0",
            "versionType": "python"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}