{
  "additionalMetadata": {
    "cna": "github_m",
    "cveId": "CVE-2024-32871",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/pimcore/pimcore/commit/38af70b3130f16fc27f2aea34e2943d7bdaaba06",
      "https://github.com/pimcore/pimcore/commit/a6821a16ea38086bf6012e682e1743488244bd85",
      "https://github.com/pimcore/pimcore/security/advisories/GHSA-277c-5vvj-9pwx"
    ]
  },
  "adp": {
    "affected": [
      {
        "collectionURL": "https://packagist.org",
        "cpes": [
          "cpe:2.3:a:pimcore:pimcore:*:*:*:*:*:*:*:*"
        ],
        "packageName": "pimcore/pimcore",
        "product": "pimcore",
        "repo": "https://github.com/pimcore/pimcore",
        "vendor": "pimcore",
        "versions": [
          {
            "lessThan": "11.2.4",
            "status": "affected",
            "version": "11.0.0",
            "versionType": "custom"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}