{
  "additionalMetadata": {
    "cna": "github_m",
    "cveId": "CVE-2024-28233",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/jupyterhub/jupyterhub/commit/e2798a088f5ad45340fe79cdf1386198e664f77f",
      "https://github.com/jupyterhub/jupyterhub/security/advisories/GHSA-7r3h-4ph8-w38g"
    ]
  },
  "adp": {
    "affected": [
      {
        "collectionURL": "https://pypi.org",
        "cpes": [
          "cpe:2.3:a:jupyter:jupyterhub:*:*:*:*:*:*:*:*"
        ],
        "packageName": "jupyterhub",
        "product": "jupyterhub",
        "vendor": "jupyterhub",
        "versions": [
          {
            "lessThan": "4.1.0",
            "status": "affected",
            "version": "0",
            "versionType": "custom"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}