{
  "additionalMetadata": {
    "cna": "github_m",
    "cveId": "CVE-2024-32481",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/vyperlang/vyper/blob/9136169468f317a53b4e7448389aa315f90b95ba/vyper/codegen/stmt.py#L286-L287",
      "https://github.com/vyperlang/vyper/commit/3de1415ee77a9244eb04bdb695e249d3ec9ed868",
      "https://github.com/vyperlang/vyper/commit/5319cfbe14951e007ccdb323257e5ada869b35d5",
      "https://github.com/vyperlang/vyper/security/advisories/GHSA-ppx5-q359-pvwj"
    ]
  },
  "adp": {
    "affected": [
      {
        "collectionURL": "https://pypi.org",
        "cpes": [
          "cpe:2.3:a:vyperlang:vyper:*:*:*:*:*:python:*:*"
        ],
        "packageName": "vyper",
        "product": "vyper",
        "vendor": "vyperlang",
        "versions": [
          {
            "lessThan": "0.4.0b1",
            "status": "affected",
            "version": "0.3.8",
            "versionType": "custom"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}